// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_EIql_VHDEHHDAcHjGmzelOF6NngYqMQ',
    appId: '1:438080546241:web:81cf5b004e8e7c24c7bb40',
    messagingSenderId: '438080546241',
    projectId: 'timecalculator-f3c48',
    authDomain: 'timecalculator-f3c48.firebaseapp.com',
    storageBucket: 'timecalculator-f3c48.appspot.com',
    measurementId: 'G-7RCJN6VKW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfcvzJQ0BbCjMu4gGpMz6LemWu_UXiuPQ',
    appId: '1:438080546241:android:fc2a059aee832addc7bb40',
    messagingSenderId: '438080546241',
    projectId: 'timecalculator-f3c48',
    storageBucket: 'timecalculator-f3c48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDQYDbo622_zp1byCf0shvSAwIMqq5JWQ',
    appId: '1:438080546241:ios:cdc761c858d2c37cc7bb40',
    messagingSenderId: '438080546241',
    projectId: 'timecalculator-f3c48',
    storageBucket: 'timecalculator-f3c48.appspot.com',
    iosClientId: '438080546241-cvntq3130s5fs04ebjiuitb6s2rb5fht.apps.googleusercontent.com',
    iosBundleId: 'com.HB.timeCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDQYDbo622_zp1byCf0shvSAwIMqq5JWQ',
    appId: '1:438080546241:ios:e35f8265985a546dc7bb40',
    messagingSenderId: '438080546241',
    projectId: 'timecalculator-f3c48',
    storageBucket: 'timecalculator-f3c48.appspot.com',
    iosClientId: '438080546241-nb8c7vqevu2uo7d9kek33pb1cvrgpvit.apps.googleusercontent.com',
    iosBundleId: 'com.HB.timeCalculator.RunnerTests',
  );
}
